# Generated by Django 4.1.7 on 2023-03-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Contact name')),
                ('surname', models.CharField(max_length=50, verbose_name='Contact surname')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone number')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.names')),
            ],
        ),
    ]
